apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openharness
resources:
  - namespace.yaml
  - config.yaml
  - app.yaml
  - gateway.yaml
  - mongo.yaml
  - rabbitmq.yaml
  - weaviate.yaml
  - guardrails.yaml
  - guardrail-evaluation.yaml
  - proxy.yaml
  - network-policy.yaml
