// Generated from spec/openharness.mapi.md of https://github.com/jeffrschneider/OpenHarness
// at commit f727de17dffe5adac4f54c7e87f3aae2afe7b864 (spec version 0.2.0). Regenerate when the spec changes.
export type SpecMethod = 'get' | 'post' | 'put' | 'patch' | 'delete' | 'ws';
export type SpecRoute = { id: string; method: SpecMethod; path: string; sse?: true };
export const specVersion = '0.2.0';
export const specRoutes: SpecRoute[] = [
  { id: 'harnesses.list', method: 'get', path: '/harnesses' },
  { id: 'harnesses.get', method: 'get', path: '/harnesses/{harnessId}' },
  { id: 'harnesses.register', method: 'post', path: '/harnesses' },
  { id: 'harnesses.update', method: 'patch', path: '/harnesses/{harnessId}' },
  { id: 'harnesses.unregister', method: 'delete', path: '/harnesses/{harnessId}' },
  { id: 'harnesses.capabilities', method: 'get', path: '/harnesses/{harnessId}/capabilities' },
  { id: 'harnesses.health', method: 'get', path: '/harnesses/{harnessId}/health' },
  {
    id: 'harnesses.validateCredentials',
    method: 'post',
    path: '/harnesses/{harnessId}/validate-credentials',
  },
  { id: 'agents.list', method: 'get', path: '/harnesses/{harnessId}/agents' },
  { id: 'agents.create', method: 'post', path: '/harnesses/{harnessId}/agents' },
  { id: 'agents.get', method: 'get', path: '/harnesses/{harnessId}/agents/{agentId}' },
  { id: 'agents.update', method: 'patch', path: '/harnesses/{harnessId}/agents/{agentId}' },
  { id: 'agents.delete', method: 'delete', path: '/harnesses/{harnessId}/agents/{agentId}' },
  { id: 'agents.clone', method: 'post', path: '/harnesses/{harnessId}/agents/{agentId}/clone' },
  { id: 'agents.export', method: 'get', path: '/harnesses/{harnessId}/agents/{agentId}/export' },
  { id: 'agents.import', method: 'post', path: '/harnesses/{harnessId}/agents/import' },
  { id: 'skills.list', method: 'get', path: '/harnesses/{harnessId}/skills' },
  { id: 'skills.register', method: 'post', path: '/harnesses/{harnessId}/skills' },
  { id: 'skills.get', method: 'get', path: '/harnesses/{harnessId}/skills/{skillId}' },
  { id: 'skills.update', method: 'patch', path: '/harnesses/{harnessId}/skills/{skillId}' },
  { id: 'skills.uninstall', method: 'delete', path: '/harnesses/{harnessId}/skills/{skillId}' },
  { id: 'skills.listVersions', method: 'get', path: '/harnesses/{harnessId}/skills/{skillId}/versions' },
  { id: 'skills.rollback', method: 'post', path: '/harnesses/{harnessId}/skills/{skillId}/rollback' },
  { id: 'skills.discover', method: 'post', path: '/harnesses/{harnessId}/skills/discover' },
  { id: 'skills.validate', method: 'post', path: '/harnesses/{harnessId}/skills/validate' },
  { id: 'skills.download', method: 'get', path: '/harnesses/{harnessId}/skills/{skillId}/download' },
  { id: 'skills.upgrade', method: 'post', path: '/harnesses/{harnessId}/skills/{skillId}/upgrade' },
  { id: 'mcp.list', method: 'get', path: '/harnesses/{harnessId}/mcp-servers' },
  { id: 'mcp.connect', method: 'post', path: '/harnesses/{harnessId}/mcp-servers' },
  { id: 'mcp.get', method: 'get', path: '/harnesses/{harnessId}/mcp-servers/{serverId}' },
  { id: 'mcp.update', method: 'patch', path: '/harnesses/{harnessId}/mcp-servers/{serverId}' },
  { id: 'mcp.disconnect', method: 'delete', path: '/harnesses/{harnessId}/mcp-servers/{serverId}' },
  { id: 'mcp.listTools', method: 'get', path: '/harnesses/{harnessId}/mcp-servers/{serverId}/tools' },
  { id: 'mcp.listResources', method: 'get', path: '/harnesses/{harnessId}/mcp-servers/{serverId}/resources' },
  { id: 'mcp.listPrompts', method: 'get', path: '/harnesses/{harnessId}/mcp-servers/{serverId}/prompts' },
  { id: 'mcp.health', method: 'post', path: '/harnesses/{harnessId}/mcp-servers/{serverId}/health' },
  { id: 'tools.list', method: 'get', path: '/harnesses/{harnessId}/tools' },
  { id: 'tools.get', method: 'get', path: '/harnesses/{harnessId}/tools/{toolId}' },
  { id: 'tools.register', method: 'post', path: '/harnesses/{harnessId}/tools' },
  { id: 'tools.unregister', method: 'delete', path: '/harnesses/{harnessId}/tools/{toolId}' },
  { id: 'tools.invoke', method: 'post', path: '/harnesses/{harnessId}/tools/{toolId}/invoke' },
  {
    id: 'tools.invokeStream',
    method: 'post',
    path: '/harnesses/{harnessId}/tools/{toolId}/invoke/stream',
    sse: true,
  },
  { id: 'execution.run', method: 'post', path: '/harnesses/{harnessId}/execute' },
  { id: 'execution.stream', method: 'post', path: '/harnesses/{harnessId}/execute/stream', sse: true },
  { id: 'execution.list', method: 'get', path: '/harnesses/{harnessId}/executions' },
  { id: 'execution.get', method: 'get', path: '/harnesses/{harnessId}/executions/{executionId}' },
  {
    id: 'execution.attachStream',
    method: 'get',
    path: '/harnesses/{harnessId}/executions/{executionId}/stream',
    sse: true,
  },
  { id: 'execution.cancel', method: 'post', path: '/harnesses/{harnessId}/executions/{executionId}/cancel' },
  { id: 'execution.result', method: 'get', path: '/harnesses/{harnessId}/executions/{executionId}/result' },
  {
    id: 'execution.listArtifacts',
    method: 'get',
    path: '/harnesses/{harnessId}/executions/{executionId}/artifacts',
  },
  {
    id: 'execution.downloadArtifact',
    method: 'get',
    path: '/harnesses/{harnessId}/executions/{executionId}/artifacts/{artifactId}',
  },
  {
    id: 'execution.listToolCalls',
    method: 'get',
    path: '/harnesses/{harnessId}/executions/{executionId}/tool-calls',
  },
  {
    id: 'execution.sendInput',
    method: 'post',
    path: '/harnesses/{harnessId}/executions/{executionId}/input',
  },
  { id: 'sessions.list', method: 'get', path: '/harnesses/{harnessId}/sessions' },
  { id: 'sessions.create', method: 'post', path: '/harnesses/{harnessId}/sessions' },
  { id: 'sessions.get', method: 'get', path: '/harnesses/{harnessId}/sessions/{sessionId}' },
  { id: 'sessions.update', method: 'patch', path: '/harnesses/{harnessId}/sessions/{sessionId}' },
  { id: 'sessions.end', method: 'delete', path: '/harnesses/{harnessId}/sessions/{sessionId}' },
  { id: 'sessions.resume', method: 'post', path: '/harnesses/{harnessId}/sessions/{sessionId}/resume' },
  { id: 'sessions.history', method: 'get', path: '/harnesses/{harnessId}/sessions/{sessionId}/history' },
  { id: 'sessions.fork', method: 'post', path: '/harnesses/{harnessId}/sessions/{sessionId}/fork' },
  { id: 'sessions.connect', method: 'ws', path: '/harnesses/{harnessId}/sessions/{sessionId}/connect' },
  { id: 'sessions.sendMessage', method: 'post', path: '/harnesses/{harnessId}/sessions/{sessionId}/message' },
  {
    id: 'sessions.sendMessageStream',
    method: 'post',
    path: '/harnesses/{harnessId}/sessions/{sessionId}/message/stream',
    sse: true,
  },
  { id: 'memory.get', method: 'get', path: '/harnesses/{harnessId}/agents/{agentId}/memory' },
  { id: 'memory.listBlocks', method: 'get', path: '/harnesses/{harnessId}/agents/{agentId}/memory/blocks' },
  {
    id: 'memory.getBlock',
    method: 'get',
    path: '/harnesses/{harnessId}/agents/{agentId}/memory/blocks/{label}',
  },
  {
    id: 'memory.updateBlock',
    method: 'put',
    path: '/harnesses/{harnessId}/agents/{agentId}/memory/blocks/{label}',
  },
  { id: 'memory.createBlock', method: 'post', path: '/harnesses/{harnessId}/agents/{agentId}/memory/blocks' },
  {
    id: 'memory.deleteBlock',
    method: 'delete',
    path: '/harnesses/{harnessId}/agents/{agentId}/memory/blocks/{label}',
  },
  { id: 'memory.search', method: 'post', path: '/harnesses/{harnessId}/agents/{agentId}/memory/search' },
  { id: 'memory.getArchive', method: 'get', path: '/harnesses/{harnessId}/agents/{agentId}/memory/archive' },
  {
    id: 'memory.addToArchive',
    method: 'post',
    path: '/harnesses/{harnessId}/agents/{agentId}/memory/archive',
  },
  { id: 'memory.export', method: 'post', path: '/harnesses/{harnessId}/agents/{agentId}/memory/export' },
  { id: 'memory.import', method: 'post', path: '/harnesses/{harnessId}/agents/{agentId}/memory/import' },
  { id: 'subagents.list', method: 'get', path: '/harnesses/{harnessId}/agents/{agentId}/subagents' },
  { id: 'subagents.spawn', method: 'post', path: '/harnesses/{harnessId}/agents/{agentId}/subagents' },
  {
    id: 'subagents.get',
    method: 'get',
    path: '/harnesses/{harnessId}/agents/{agentId}/subagents/{subagentId}',
  },
  {
    id: 'subagents.terminate',
    method: 'delete',
    path: '/harnesses/{harnessId}/agents/{agentId}/subagents/{subagentId}',
  },
  {
    id: 'subagents.delegate',
    method: 'post',
    path: '/harnesses/{harnessId}/agents/{agentId}/subagents/{subagentId}/delegate',
  },
  {
    id: 'subagents.delegateStream',
    method: 'post',
    path: '/harnesses/{harnessId}/agents/{agentId}/subagents/{subagentId}/delegate/stream',
    sse: true,
  },
  {
    id: 'subagents.result',
    method: 'get',
    path: '/harnesses/{harnessId}/agents/{agentId}/subagents/{subagentId}/result',
  },
  {
    id: 'subagents.attachStream',
    method: 'get',
    path: '/harnesses/{harnessId}/agents/{agentId}/subagents/{subagentId}/stream',
    sse: true,
  },
  { id: 'files.list', method: 'get', path: '/harnesses/{harnessId}/files' },
  { id: 'files.read', method: 'get', path: '/harnesses/{harnessId}/files/{path}' },
  { id: 'files.write', method: 'put', path: '/harnesses/{harnessId}/files/{path}' },
  { id: 'files.delete', method: 'delete', path: '/harnesses/{harnessId}/files/{path}' },
  { id: 'files.search', method: 'post', path: '/harnesses/{harnessId}/files/search' },
  { id: 'files.upload', method: 'post', path: '/harnesses/{harnessId}/files/upload' },
  { id: 'files.uploadBatch', method: 'post', path: '/harnesses/{harnessId}/files/upload-batch' },
  { id: 'files.download', method: 'get', path: '/harnesses/{harnessId}/files/{path}/download' },
  { id: 'files.downloadBatch', method: 'post', path: '/harnesses/{harnessId}/files/download-batch' },
  { id: 'files.mkdir', method: 'post', path: '/harnesses/{harnessId}/files/mkdir' },
  { id: 'hooks.list', method: 'get', path: '/harnesses/{harnessId}/hooks' },
  { id: 'hooks.register', method: 'post', path: '/harnesses/{harnessId}/hooks' },
  { id: 'hooks.get', method: 'get', path: '/harnesses/{harnessId}/hooks/{hookId}' },
  { id: 'hooks.update', method: 'patch', path: '/harnesses/{harnessId}/hooks/{hookId}' },
  { id: 'hooks.unregister', method: 'delete', path: '/harnesses/{harnessId}/hooks/{hookId}' },
  { id: 'hooks.streamEvents', method: 'get', path: '/harnesses/{harnessId}/events/stream', sse: true },
  { id: 'hooks.listEvents', method: 'get', path: '/harnesses/{harnessId}/events' },
  { id: 'webhooks.register', method: 'post', path: '/harnesses/{harnessId}/webhooks' },
  { id: 'webhooks.list', method: 'get', path: '/harnesses/{harnessId}/webhooks' },
  { id: 'webhooks.delete', method: 'delete', path: '/harnesses/{harnessId}/webhooks/{webhookId}' },
  { id: 'planning.get', method: 'get', path: '/harnesses/{harnessId}/executions/{executionId}/plan' },
  { id: 'planning.update', method: 'patch', path: '/harnesses/{harnessId}/executions/{executionId}/plan' },
  {
    id: 'planning.listTasks',
    method: 'get',
    path: '/harnesses/{harnessId}/executions/{executionId}/plan/tasks',
  },
  {
    id: 'planning.updateTask',
    method: 'patch',
    path: '/harnesses/{harnessId}/executions/{executionId}/plan/tasks/{taskId}',
  },
  {
    id: 'planning.stream',
    method: 'get',
    path: '/harnesses/{harnessId}/executions/{executionId}/plan/stream',
    sse: true,
  },
  { id: 'conformance.run', method: 'post', path: '/harnesses/{harnessId}/conformance/run' },
  {
    id: 'conformance.stream',
    method: 'get',
    path: '/harnesses/{harnessId}/conformance/run/stream',
    sse: true,
  },
  { id: 'conformance.results', method: 'get', path: '/harnesses/{harnessId}/conformance/results' },
  { id: 'conformance.status', method: 'get', path: '/harnesses/{harnessId}/conformance/status' },
  { id: 'diagnostics.get', method: 'get', path: '/harnesses/{harnessId}/diagnostics' },
  { id: 'diagnostics.logs', method: 'get', path: '/harnesses/{harnessId}/logs' },
  { id: 'diagnostics.streamLogs', method: 'get', path: '/harnesses/{harnessId}/logs/stream', sse: true },
];
